### ISSUE TITLE
how about ffmpeg 3.2.x

### ISSUE THREAD

**Issue by vvhh2002** [targodan/ffgopeg#5]
has any plan for 3.2.x api ?

**Comment by vvhh2002** [comment]
ok, I find develop branch has 3.2.4 . Thanks , good work!

**Comment by targodan** [comment]
I don't see any reason why not. In fact travis-ci is testing this project against 3.2.x as well, without problems so far. 

Note that any new features from 3.2 won't be available without a little work though. Is there any particular new feature from 3.2 you want?
